# Generated by Django 5.2.17 on 2026-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('failed_count', models.PositiveSmallIntegerField(default=0, verbose_name='falhas seguidas')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado até')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'controle de tentativas de login',
                'verbose_name_plural': 'controles de tentativas de login',
            },
        ),
    ]
