# Generated by Django 5.2.17 on 2026-10-05 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Entrada'), ('expense', 'Despesa')], max_length=7, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('date', models.DateField(verbose_name='data')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['user', '-date', '-id'], name='transactions_user_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transactions_amount_gt_0')],
            },
        ),
    ]
